# SPDX-License-Identifier: PMPL-1.0-or-later

homepage: "https://github.com/hyperpolymath/protocol-squisher"
language: rust
primary_contact: "j.d.a.jewell@open.ac.uk"
auto_ccs:
  - "j.d.a.jewell@open.ac.uk"
sanitizers:
  - address
  - undefined
  - memory
